namespace InterviewAssistant.Core.Reports;

/// <summary>Report section labels in the 10 launch languages (native review pending — see MULTILINGUAL_VALIDATION.md).</summary>
public static class ReportLabels
{
    public static readonly string[] Keys =
    {
        "title", "honesty", "questions", "category", "mode", "suggestions", "original", "language", "difficulty", "stories", "metrics",
        "repeated", "notcovered", "gaps", "interruptions", "latency", "transcription", "strengths", "weaknesses", "followup", "thankyou",
        "unused", "inference", "none", "duration",
    };

    private static readonly Dictionary<string, string[]> T = new()
    {
        ["en"] = new[] { "Interview report", "The candidate microphone was OFF: this report records the interviewer's questions and the suggestions shown, not what you actually said. It is not an assessment of your spoken performance.", "Questions asked", "Category", "Mode", "Suggestions shown", "Original wording", "Language", "Difficulty areas", "Stories recommended", "Metrics recommended", "Repeated topics", "Job topics not covered", "Experience-gap questions", "Interruptions / fast follow-ups (estimated)", "Response latency", "Transcription notes", "Strengths of the preparation", "Preparation gaps", "Suggested follow-up preparation", "Thank-you / follow-up themes", "Relevant stories not used", "Inference", "None", "Duration" },
        ["es"] = new[] { "Informe de la entrevista", "El micrófono del candidato estaba DESACTIVADO: este informe registra las preguntas del entrevistador y las sugerencias mostradas, no lo que usted dijo. No evalúa su desempeño oral.", "Preguntas realizadas", "Categoría", "Modo", "Sugerencias mostradas", "Texto original", "Idioma", "Áreas de dificultad", "Historias recomendadas", "Métricas recomendadas", "Temas repetidos", "Temas del puesto no tratados", "Preguntas sobre experiencia no demostrada", "Interrupciones / preguntas rápidas (estimado)", "Latencia de respuesta", "Notas de transcripción", "Fortalezas de la preparación", "Carencias de la preparación", "Preparación de seguimiento sugerida", "Temas para el agradecimiento", "Historias relevantes no usadas", "Inferencia", "Ninguno", "Duración" },
        ["fr"] = new[] { "Rapport d'entretien", "Le micro du candidat était DÉSACTIVÉ : ce rapport enregistre les questions du recruteur et les suggestions affichées, pas ce que vous avez réellement dit. Ce n'est pas une évaluation de votre prestation orale.", "Questions posées", "Catégorie", "Mode", "Suggestions affichées", "Formulation originale", "Langue", "Points difficiles", "Exemples recommandés", "Chiffres recommandés", "Sujets répétés", "Sujets du poste non abordés", "Questions sur une expérience manquante", "Interruptions / relances rapides (estimation)", "Latence de réponse", "Notes de transcription", "Points forts de la préparation", "Lacunes de la préparation", "Préparation complémentaire suggérée", "Thèmes pour le message de remerciement", "Exemples pertinents non utilisés", "Déduction", "Aucun", "Durée" },
        ["de"] = new[] { "Interviewbericht", "Das Mikrofon des Kandidaten war AUS: Dieser Bericht enthält die Fragen des Interviewers und die angezeigten Vorschläge, nicht das, was Sie tatsächlich gesagt haben. Er bewertet nicht Ihre mündliche Leistung.", "Gestellte Fragen", "Kategorie", "Modus", "Angezeigte Vorschläge", "Originalformulierung", "Sprache", "Schwierige Bereiche", "Empfohlene Beispiele", "Empfohlene Kennzahlen", "Wiederholte Themen", "Nicht behandelte Themen der Stelle", "Fragen zu fehlender Erfahrung", "Unterbrechungen / schnelle Nachfragen (geschätzt)", "Antwortlatenz", "Hinweise zur Transkription", "Stärken der Vorbereitung", "Lücken in der Vorbereitung", "Empfohlene weitere Vorbereitung", "Themen für die Dankesnachricht", "Relevante, nicht genutzte Beispiele", "Ableitung", "Keine", "Dauer" },
        ["pt"] = new[] { "Relatório da entrevista", "O microfone do candidato estava DESLIGADO: este relatório registra as perguntas do entrevistador e as sugestões exibidas, não o que você realmente disse. Não é uma avaliação do seu desempenho oral.", "Perguntas feitas", "Categoria", "Modo", "Sugestões exibidas", "Texto original", "Idioma", "Áreas de dificuldade", "Histórias recomendadas", "Métricas recomendadas", "Temas repetidos", "Temas da vaga não abordados", "Perguntas sobre experiência não comprovada", "Interrupções / perguntas rápidas (estimativa)", "Latência de resposta", "Notas de transcrição", "Pontos fortes da preparação", "Lacunas da preparação", "Preparação complementar sugerida", "Temas para o agradecimento", "Histórias relevantes não usadas", "Inferência", "Nenhum", "Duração" },
        ["it"] = new[] { "Report del colloquio", "Il microfono del candidato era SPENTO: questo report registra le domande dell'intervistatore e i suggerimenti mostrati, non ciò che hai effettivamente detto. Non è una valutazione della tua esposizione orale.", "Domande poste", "Categoria", "Modalità", "Suggerimenti mostrati", "Formulazione originale", "Lingua", "Aree di difficoltà", "Esempi consigliati", "Metriche consigliate", "Temi ripetuti", "Temi del ruolo non trattati", "Domande su esperienze mancanti", "Interruzioni / domande rapide (stima)", "Latenza della risposta", "Note di trascrizione", "Punti di forza della preparazione", "Lacune della preparazione", "Preparazione successiva consigliata", "Temi per il ringraziamento", "Esempi pertinenti non usati", "Deduzione", "Nessuno", "Durata" },
        ["ar"] = new[] { "تقرير المقابلة", "كان ميكروفون المرشح متوقفًا: يسجل هذا التقرير أسئلة المحاور والاقتراحات المعروضة، وليس ما قلته فعليًا. وهو ليس تقييمًا لأدائك الشفهي.", "الأسئلة المطروحة", "الفئة", "النمط", "الاقتراحات المعروضة", "الصياغة الأصلية", "اللغة", "مجالات الصعوبة", "القصص الموصى بها", "المؤشرات الموصى بها", "مواضيع متكررة", "مواضيع الوظيفة التي لم تُطرح", "أسئلة عن خبرة غير موجودة", "مقاطعات / أسئلة متتابعة سريعة (تقديري)", "زمن الاستجابة", "ملاحظات النسخ", "نقاط قوة التحضير", "ثغرات التحضير", "تحضير إضافي مقترح", "أفكار لرسالة الشكر", "قصص مناسبة لم تُستخدم", "استنتاج", "لا شيء", "المدة" },
        ["fa"] = new[] { "گزارش مصاحبه", "میکروفون داوطلب خاموش بود: این گزارش پرسش‌های مصاحبه‌گر و پیشنهادهای نمایش‌داده‌شده را ثبت می‌کند، نه آنچه شما واقعاً گفتید. این گزارش ارزیابی عملکرد گفتاری شما نیست.", "پرسش‌های مطرح‌شده", "دسته", "حالت", "پیشنهادهای نمایش‌داده‌شده", "متن اصلی", "زبان", "حوزه‌های دشوار", "داستان‌های پیشنهادشده", "شاخص‌های پیشنهادشده", "موضوعات تکراری", "موضوعات شغل که مطرح نشد", "پرسش‌های مربوط به تجربه‌ای که ندارید", "قطع صحبت / پرسش‌های پیاپی سریع (تخمینی)", "تأخیر پاسخ", "نکات رونویسی", "نقاط قوت آمادگی", "کمبودهای آمادگی", "آمادگی تکمیلی پیشنهادی", "محورهای پیام تشکر", "داستان‌های مرتبط استفاده‌نشده", "استنباط", "هیچ", "مدت" },
        ["zh"] = new[] { "面试报告", "候选人麦克风已关闭：本报告记录面试官的问题和显示的建议，而不是你实际说的话。它不是对你口头表现的评估。", "提出的问题", "类别", "模式", "显示的建议", "原始措辞", "语言", "难点", "推荐的经历", "推荐的指标", "重复的话题", "未涉及的职位话题", "关于缺乏经验的问题", "打断 / 快速追问（估计）", "响应延迟", "转写说明", "准备工作的优势", "准备工作的不足", "建议的后续准备", "感谢信主题", "未使用的相关经历", "推断", "无", "时长" },
        ["hi"] = new[] { "इंटरव्यू रिपोर्ट", "उम्मीदवार का माइक्रोफ़ोन बंद था: यह रिपोर्ट इंटरव्यूअर के प्रश्न और दिखाए गए सुझाव दर्ज करती है, न कि आपने वास्तव में क्या कहा। यह आपके बोलने के प्रदर्शन का मूल्यांकन नहीं है।", "पूछे गए प्रश्न", "श्रेणी", "मोड", "दिखाए गए सुझाव", "मूल शब्द", "भाषा", "कठिन क्षेत्र", "सुझाई गई कहानियाँ", "सुझाए गए आँकड़े", "दोहराए गए विषय", "नौकरी के विषय जो नहीं आए", "अनुभव की कमी वाले प्रश्न", "रुकावटें / तेज़ अगले प्रश्न (अनुमानित)", "प्रतिक्रिया में देरी", "ट्रांसक्रिप्शन नोट्स", "तैयारी की ताकतें", "तैयारी की कमियाँ", "सुझाई गई आगे की तैयारी", "धन्यवाद संदेश के विषय", "उपयोग न की गई प्रासंगिक कहानियाँ", "अनुमान", "कोई नहीं", "अवधि" },
    };

    public static IReadOnlyCollection<string> Languages => T.Keys;

    public static string Get(string lang, string key)
    {
        var arr = T.GetValueOrDefault(Languages.Contains(lang) ? lang : "en") ?? T["en"];
        var i = Array.IndexOf(Keys, key);
        return i >= 0 && i < arr.Length ? arr[i] : key;
    }

    public static bool IsComplete(string lang) => T.TryGetValue(lang, out var a) && a.Length == Keys.Length && a.All(s => !string.IsNullOrWhiteSpace(s));
}
